### ISSUE TITLE
Nanopass uses an excessive amount of memory

### ISSUE THREAD

**Issue by eholk** [akeep/nanopass-framework#4]
I'm seeing the Harlan compiler regularly use about 3GB of memory to do all the Nanopass macro expansions. This is kind of a lot, and it also means we have to use the 64-bit version of Petite or Chez to compile programs. Is there a way to significantly reduce this?

**Comment by akeep** [comment]
Issue moved to new repository: [nanopass/nanopass-framework-scheme](https://github.com/akeep/nanopass-framework/issues)

**Comment by jasonknight** [comment]
I am unable to build due to this issue, it seems it hasn't been fixed. Is there no better way to compile this than on a system with > 3GB of memory?

**Comment by eholk** [comment]
Out of curiosity, are you running Petite or full Chez Scheme? Chez Scheme is open source now, so it's worth giving a try if you are having trouble with Petite.

**Comment by jasonknight** [comment]
I am running ChezScheme. A simple solution to the problem user side is to spool up a Virtual Machine with the same OS as the target server (in my case Debian 9 amd64) and make sure it has > 3G of ram assigned, build, then rsync to the server and finally run make install. Worked like a charm. 

The only issue is that the target server has less memory than needed to compile scheme. 

Now I can use Scheme on my servers, which makes me a happy bunny.
